### ISSUE TITLE
Results tables - summary: limited to 1000

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/im-tables-3#57]
From @kkarra

>Currently it looks like when the Results table display more than 1000 rows, the ‘bar-chart/View column summary’ button does not do much..is that true? I used to think that it did filter at least on the 1000 values it displays in the pop-up table, but that doesn’t seem to be the case.
>
>try it here:
>http://www.flymine.org/flymine/template.do?name=Chromosome_Gene&scope=global
>
>So, we are curious if this could be made to work with a higher cut-off value say 5000?  Is that doable/configurable? Would it make things slow, is that why it was not enabled to begin with?

**Comment by yochannah** [comment]
Gos reports the column summary works fine on 285k rows on flymine - let's check how that is implemented and emulate it in imtables

**Comment by heralden** [comment]
im-tables-3 is currently fetching results for all items to create a column summary, resulting in a massive payload for something with a lot of rows.

@yochannah told me about the undocumented `summaryPath` parameter that can be used with `POST /query/results`, making it respond with a summary instead. By using this, we could probably remove the limit for column summaries.

Edit: It **does** actually use `summaryPath`, but doesn't grab the full result if there are more than 1000 unique values. Why it's like this, I cannot understand. Since setting `size=1000` would only return the top 1000 values anyways, so it doesn't matter how many unique values there are as the rest would just be ignored.
